ESP-IDF Component Continuous Integration
OpenCyphal/libcanard pull request #229
Opened 2024-09-16 21:18 UTC by manforowicz

This pull request is meant to resolve #227 by adding continuous integration for publishing Libcanard to the [ESP Component Registry](https://components.espressif.com/).

Files added:
- `idf_component.yml`. This file contains required ESP component metadata.
- `Kconfig`. ESP components use this file as a standard way for controlling build options. I've added options for enabling/disabling assertions and the CRC table.
- `CMakeLists.txt`. This file is required to register the component with the ESP build system.
- `.github/workflows/esp_publish.yml`. This workflow uploads the component to the ESP-IDF registry whenever a new GitHub release is published.
- `.github/workflows/esp_dry_run.yml`. This workflow does a dry-run of uploading to the ESP-IDF registry, without publishing anything. It can only be manually triggered. I've tested this in my repository, and it seems to work.

2024-09-17 11:43 UTC, pavel-kirienko requested changes
Thank you. I have created the token and added it to the repository secrets.

2024-09-17 11:43 UTC, pavel-kirienko commented on CMakeLists.txt
Is it possible to hide `CMakeLists.txt`, `Kconfig`, and `idf_component.yml` into a subdirectory, or at least the first two? I don't want to pollute the project root with third-party items.

2024-09-17 11:43 UTC, pavel-kirienko commented on idf_component.yml
> +description: "OpenCyphal for embedded systems."
```suggestion
description: "Cyphal/CAN for embedded systems."
```

Cyphal comes with various transports, CAN is only one of them.

2024-09-17 11:50 UTC, pavel-kirienko commented on CMakeLists.txt
This appears to be doable via [`repository_info`](https://docs.espressif.com/projects/idf-component-manager/en/latest/reference/manifest_file.html#repository-info)

2024-09-17 17:51 UTC, manforowicz commented
As you suggested, to avoid polluting the root of the repository with ESP-related files, I tried using [`repository_info`](https://docs.espressif.com/projects/idf-component-manager/en/latest/reference/manifest_file.html#repository-info) and putting the ESP-related files into a subdirectory. However, this didn't work because ESP-IDF gets confused whenever the source code files are not in the directory where `CMakeLists.txt` is.

So I decided it would be cleanest to just have the continuous integration script copy all the required files into a temporary component directory before publishing. I tested the `esp_dry_run.yml` workflow locally, and it seems to work correctly.

2024-09-17 20:22 UTC, pavel-kirienko submitted a review, later dismissed
Looks good. Please address the last two nits and we'll merge it.

2024-09-17 20:22 UTC, pavel-kirienko commented on .github/workflows/package_esp_component.sh
Shouldn't the script go into `/esp_metadata`?

2024-09-17 20:22 UTC, pavel-kirienko commented on esp_metadata/Kconfig
> +endmenu
Missing newline at the end

2024-09-18 12:20 UTC, pavel-kirienko approved these changes

2024-09-18 12:21 UTC, merged